### ISSUE TITLE
Documentatie

### ISSUE THREAD

**Issue by rvmourik** [boekuwzending/php-sdk#4]
Online documentatie opstellen i.p.v. via Readme.md

**Comment by rvmourik** [comment]
@petervanackooij ik begreep van Margreet en Marco dat je bezig bent geweest met Zendesk voor documentatie. Wil je hier de PHP-SDK ook in opnemen?

**Comment by petervanackooij** [comment]
Nog niet aan gedacht, maar die mag er zeker in.

**Comment by rvmourik** [comment]
Documentatie issue is aangemaakt in de documentation repository.

https://github.com/boekuwzending/documentation/issues/1
